'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Card from '@/components/ui/Card';
import Input from '@/components/ui/Input';
import Button from '@/components/ui/Button';

export default function LoginPage() {
  const router = useRouter();
  const [tokenId, setTokenId] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!tokenId.trim()) {
      setError('Please enter your token ID');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token_id: tokenId }),
      });

      const data = await res.json();

      if (data.success) {
        // Save token to localStorage
        localStorage.setItem('access_token', data.data.access_token);
        localStorage.setItem('user', JSON.stringify(data.data.user));

        // Redirect based on role
        if (data.data.user.role === 'admin') {
          router.push('/admin');
        } else {
          router.push('/cr');
        }
      } else {
        setError(data.error || 'Invalid token ID');
      }
    } catch (err) {
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-200px)] flex items-center justify-center px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
            <span className="text-white text-2xl">🔐</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Login to System
          </h1>
          <p className="text-gray-600">
            Enter your token ID to access the system
          </p>
        </div>

        <Card>
          <form onSubmit={handleLogin} className="space-y-6">
            <Input
              label="Token ID"
              type="text"
              placeholder="Enter your token ID (e.g., ADMIN2024)"
              value={tokenId}
              onChange={(e) => setTokenId(e.target.value.toUpperCase())}
              error={error}
              autoFocus
            />

            <Button
              type="submit"
              isLoading={loading}
              className="w-full"
              size="lg"
            >
              Login
            </Button>
          </form>

          <div className="mt-6 p-4 bg-blue-50 rounded-lg">
            <h3 className="text-sm font-medium text-blue-900 mb-2">
              💡 Demo Credentials
            </h3>
            <div className="text-sm text-blue-700 space-y-1">
              <p>Admin: <code className="bg-blue-100 px-2 py-0.5 rounded">ADMIN2024</code></p>
              <p className="text-xs text-blue-600 mt-2">
                Note: CR tokens are generated by admin
              </p>
            </div>
          </div>
        </Card>

        <div className="mt-6 text-center">
          <p className="text-sm text-gray-500">
            Don't have a token?{' '}
            <a href="#" className="text-blue-600 hover:text-blue-700 font-medium">
              Contact Admin
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}